### ISSUE TITLE
fix parent rule: should depend on OWN measuretype, not their parent's

### ISSUE THREAD

**Issue by tmfrnz** [marine-defrag/marine-defrag-server#99]

**Comment by tmfrnz** [comment]
@parndt, see comment on test: 
https://github.com/dumparkltd/marine-defrag-server/pull/100#pullrequestreview-1037400639

**Comment by tmfrnz** [comment]
@parndt just wondering if you can still have a look?

**Comment by parndt** [comment]
> @parndt just wondering if you can still have a look?

yup! @tmfrnz will still look at this 😄
